
# Use an official Node.js image as the base
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY api/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY api/ .

# Expose the port the app runs on
EXPOSE 5000

# Start the application
CMD ["npm", "start"]
